# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-10 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('test', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.time)),
            ],
        ),
    ]
